- name: Create a simple VM instance
  hosts: localhost
  connection: local
  tasks:
    - name: Deploy new VM instance
      ec2:
        key_name: "{{ aws_keypair }}"
        instance_type: t2.micro
        image: ami-b6a016d9
        wait: yes
        count: 1
        vpc_subnet_id: "{{ id_subnet }}"
        assign_public_ip: yes
        region: eu-central-1
