- name: Create a simple VM instance
  hosts: localhost
  connection: local
  tasks:
    - name: Deploy new VM instance
      ec2:
        key_name: mykey
        instance_type: t2.micro
        image: ami-26ebbc5c
        wait: yes
        count: 1
        vpc_subnet_id: "{{ id_subnet }}"
        assign_public_ip: yes
        group: server
        region: us-east-1
